---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ultb6792/public_html/rwtest/
    #- /bin/cp -r * $DEPLOYPATH #copy all from root
    - /bin/cp -r * ./public/ $DEPLOYPATH
   # - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/css
